name: ASPNET API CI/CD

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1

jobs:

#  BUILD 
  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.out.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Image
        id: out
        run: |
          IMAGE="${{ vars.ECR_REPOSITORY }}:${{ github.run_number }}"

          docker build -t $IMAGE .
          docker push $IMAGE

          echo "image=$IMAGE" >> $GITHUB_OUTPUT


#  DETECT SLOT 
  detect-slot:
    runs-on: ubuntu-latest
    needs: build

    outputs:
      deploy_service: ${{ steps.slot.outputs.deploy_service }}
      deploy_tg: ${{ steps.slot.outputs.deploy_tg }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Detect Slot
        id: slot
        run: bash infra/scripts/detect_slot.sh
        env:
          ALB_LISTENER_ARN: ${{ vars.ALB_LISTENER_ARN }}
          BLUE_TG_ARN: ${{ vars.BLUE_TG_ARN }}
          GREEN_TG_ARN: ${{ vars.GREEN_TG_ARN }}
          BLUE_SERVICE: ${{ vars.BLUE_SERVICE }}
          GREEN_SERVICE: ${{ vars.GREEN_SERVICE }}
          AWS_REGION: ${{ env.AWS_REGION }}


# - DEPLOY 
  deploy:
    runs-on: ubuntu-latest
    needs: [build, detect-slot]

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Register Task Definition
        id: register
        run: bash infra/scripts/register_task.sh
        env:
          IMAGE_URI: ${{ needs.build.outputs.image }}

      - name: Deploy ECS Service
        run: bash infra/scripts/deploy.sh
        env:
          ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
          TASK_DEF_ARN: ${{ env.TASK_DEF_ARN }}
          DEPLOY_SERVICE: ${{ needs.detect-slot.outputs.deploy_service }}

      - name: Switch Traffic
        run: bash infra/scripts/switch_traffic.sh
        env:
          ALB_LISTENER_ARN: ${{ vars.ALB_LISTENER_ARN }}
          DEPLOY_TG_ARN: ${{ needs.detect-slot.outputs.deploy_tg }}